Chetan katkar

Assignment - 03

R programming

11/10/26

git repo : https://github.com/Chetan-Katkar/Air-Quality-Data-Cleaning-R

**R as a Calculator**

Power operator

In [1]:
2^3

[1] 8

In [2]:
2**3

[1] 8

In [3]:
2^0.5

[1] 1.414214

In [4]:
2^-0.5

[1] 0.7071068

vector operations

In [5]:
c(2,3,5,7)^2

[1]  4  9 25 49

In [7]:
c(2,3,5,7)^c(2,3)

[1]   4  27  25 343

Integer division with scalar

In [8]:
2 %/% 2

[1] 1

In [9]:
3 %/% 2

[1] 1

Integer division with vectors

In [10]:
c(1, 2, 3, 4) %/% 3

[1] 0 0 1 1

In [11]:
c(2,3,5,7)%/%c(2,3)

[1] 1 1 2 2

Modulo division

In [12]:
2 %% 2

[1] 0

vector modulo divided by scalar

In [13]:
c(1, 2, 3, 4) %% 3

[1] 1 2 0 1

Vector modulo vector

In [14]:
c(2,3,5,7)%%c(2,3)

[1] 0 0 1 1

Max and Min function

In [15]:
max(1 , 2, 3)

[1] 3

In [16]:
min(1 , 2, 3)

[1] 1

Arithmetic Functions

In [17]:
mean(c(2, 3, 4))

[1] 3

In [18]:
abs(-4)
abs(4)

[1] 4

[1] 4

In [19]:
sqrt(4)
sqrt(c(2, 4, 5, 6))

[1] 2

[1] 1.414214 2.000000 2.236068 2.449490

In [20]:
sum(c(2, 3,4,5))

[1] 14

In [21]:
prod(c(2, 3,4,5))

[1] 120

In [23]:
round(1.234545)
round(1.83)

[1] 1

[1] 2

In [25]:
log(10)
log(exp(2))
log10(100)

[1] 2.302585

[1] 2

[1] 2

Assignment

In [27]:
x1 = c(2,3,4,5)
x1

[1] 2 3 4 5

Matrix

In [31]:
x = matrix(nrow = 2, ncol = 2, data = c(1, 2 , 3,4))
x
x[1, 2]

     [,1] [,2]
[1,] 1    3
[2,] 2    4

[1] 3

In [41]:
x = matrix(nrow = 2, ncol = 2, data = c(1, 2.43 , 3,FALSE), byrow = TRUE)
x

     [,1] [,2]
[1,] 1    2.43
[2,] 3    0.00

methods of matrices

In [35]:
dim(x)
nrow(x)
ncol(x)

[1] 2 2

[1] 2

[1] 2

In [39]:
mode(x)

[1] "numeric"